### ISSUE TITLE
Array field could not be filtered as $ne

### ISSUE THREAD

**Issue by yasek** [marrow/mongo#43]
Subj, I'm getting error like 

Q(SomeType, 'some_field', Array('some_field', kind=Reference('<anonymous>', kind='some_class'))) does not allow $ne comparison.

**Comment by amcgregor** [comment]
Howdy!

Do you have a small sample case to reproduce the problem?  Just enough model and the line or lines needed to cause the exception.

Have you tested with the latest develop branch, not just the released version?  There have been some changes to field comparability (mostly `Embed`) that my have incidentally resolved your issue.

**Comment by yasek** [comment]
Sure, what I'm trying to do is

```
from marrow.mongo import Document
from marrow.mongo.field import Array, Integer

class A(Document):
    field = Array(Integer())

print A.field != 1
```

**Comment by amcgregor** [comment]
Excellent catch!  Two issues this identified have been corrected:

* The development-time validation checks were incorrectly getting the intersection instead of combined set of operator aliases.
* The `Array` field did not define relative and equality operators as allowed.

Your test code now generates the correct `Filter` document.
